coverage_service: cobertura_xml
workspace: QuickTableViewController.xcworkspace
xcodeproj: QuickTableViewController.xcodeproj
scheme: QuickTableViewController-iOS
source_directory: Source
output_directory: test_output/xml_report
ignore:
  - Carthage/*
  - Example/*
  - QuickTableViewControllerTests/*
  - Pods/*
