disabled_rules:
  - cyclomatic_complexity
  - force_cast
  - function_body_length
  - valid_docs
  - vertical_whitespace
opt_in_rules:
  - attributes
  - explicit_init
  - explicit_top_level_acl
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
included:
  - Example
  - QuickTableViewControllerTests
  - Source
excluded:
  - Carthage
  - Pods
line_length: 192
