disabled_rules:
  - cyclomatic_complexity
  - force_cast
  - function_body_length
  - valid_docs
  - vertical_whitespace
opt_in_rules:
  - explicit_init
  - operator_usage_whitespace
included:
  - Example
  - QuickTableViewControllerTests
  - Source
excluded:
  - Carthage
  - Pods
line_length: 192
