disabled_rules:
  - cyclomatic_complexity
  - force_cast
  - function_body_length
  - valid_docs
included:
  - Example
  - QuickTableViewControllerTests
  - Source
excluded:
  - Carthage
  - Pods
line_length: 192
