language: objective-c
osx_image: xcode7.3
matrix:
  include:
    - env: SCHEME=Example
    - env: SCHEME=QuickTableViewController-iOS
      before_script:
        - bundle exec danger
cache:
  bundler: true
  directories:
  - vendor/bundle
  - Pods
before_install:
  - export LANG=en_US.UTF-8
  - brew update
  - brew tap homebrew/bundle
  - brew bundle
install:
  - bundle install --without development --deployment --jobs=3 --retry=3
  - bundle exec pod install --no-repo-update
  - carthage bootstrap --no-use-binaries --platform ios
script:
  - bundle exec scan --scheme $SCHEME
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - make coverage
notifications:
  email: false
