name: Docs
on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: Source
          module-name: QuickTableViewController
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: ".build/documentation"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_WIKI_PUBLISH_ACTION }}
