name: Unit tests
on: push

jobs:
  test:
    name: build and test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'
      - name: Bundle install
        run: |
          gem install bundler:2.1.4
          bundle install --without development --deployment --jobs=3 --retry=3
      - name: Test
        run: |
          bundle exec rake "test:ios[QuickTableViewController-iOS]"
          bundle exec rake "test:tvos[QuickTableViewController-tvOS]"
      - name: Report coverage
        run: |
          bash <(curl -s https://codecov.io/bash) -cF ios -J "QuickTableViewController"
